### ISSUE TITLE
[Bug]: Error "Malformed UTF-8 characters, possibly incorrectly encoded"

### ISSUE THREAD

**Issue by ZhenyaSharin** [spatie/laravel-pdf#106]
### What happened?

I tried to do a test API request and I've got error exception with error message: "Malformed UTF-8 characters, possibly incorrectly encoded".

### How to reproduce the bug

Test-method in the controller:

public function pdf()
{
       Pdf::view('pdfs.pdftest')
            ->format('a4')
            ->save('test.pdf');
}

### Package Version

1.4

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by Zboru** [comment]
How did you fixed this issue?

**Comment by MelomiLight** [comment]
how?
