### ISSUE TITLE
[Bug]: puppeteer requirement

### ISSUE THREAD

**Issue by mahsa-jannaty** [spatie/laravel-pdf#14]
### What happened?

i got this error and i think its because of a missing requirement named "puppeteer"
I'm trying to run npm i puppeteer --save but its not finished yet...

`The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/Applications/MAMP/htdocs/blog8/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/var\/tmp\/591852933-0296545001704295729\/index.html","action":"pdf","options":{"path":"\/Applications\/MAMP\/htdocs\/blog8\/public\/testSpatieLaravel.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false}}'" failed. Exit Code: 1(General error) Working directory: /Applications/MAMP/htdocs/blog8/public Output: ================ Error Output: ================ node:internal/modules/cjs/loader:1144 const err = new Error(message); ^ Error: Cannot find module 'puppeteer' Require stack: - /Applications/MAMP/htdocs/blog8/vendor/spatie/browsershot/bin/browser.cjs at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15) at Module._load (node:internal/modules/cjs/loader:985:27) at Module.require (node:internal/modules/cjs/loader:1235:19) at require (node:internal/modules/helpers:176:18) at callChrome (/Applications/MAMP/htdocs/blog8/vendor/spatie/browsershot/bin/browser.cjs:67:28) at Object.<anonymous> (/Applications/MAMP/htdocs/blog8/vendor/spatie/browsershot/bin/browser.cjs:424:5) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) { code: 'MODULE_NOT_FOUND', requireStack: [ '/Applications/MAMP/htdocs/blog8/vendor/spatie/browsershot/bin/browser.cjs' ] } Node.js v21.4.0`

### How to reproduce the bug

on first test on a fresh Laravel 10

### Package Version

1.0.0

### PHP Version

8.2.0

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by neurotools** [comment]
It doesn't mention other platform requirements un the documentation, but uses Pupeteer, Browsershot, Chromium... It's not a "pure PHP" solution.

**Comment by freekmurze** [comment]
The requirements are mentioned here: https://spatie.be/docs/laravel-pdf/v1/requirements
