### ISSUE TITLE
[Bug]: Footer view cannot be set

### ISSUE THREAD

**Issue by alexmanase** [spatie/laravel-pdf#157]
### What happened?

I can't set the footer view when generating a PDF.

### How to reproduce the bug

1. Create a view for a PDF.
2. Create a view for the footer.
3. Return a PDF response.

### Package Version

1.5.1

### PHP Version

8.3.8

### Laravel Version

^11.0

### Which operating systems does with happen with?

macOS, Linux

### Notes

I've created a repo for reproduction:
1. Clone `https://github.com/alexmanase/spatie-laravel-pdf-demo`
2. `composer install`
3. `php artisan key:generate --ansi`
4. Go to `web.php`, there is the code for generating the PDF.
5. Observe that the footer is not shown in the generated PDF.

**Comment by ArielMejiaDev** [comment]
@alexmanase did you set a font-size for the footer, this value is required for headers and footers

**Comment by alexmanase** [comment]
You are right.

Thank you!
