### ISSUE TITLE
[Bug]: header, footer not showing

### ISSUE THREAD

**Issue by hurycz** [spatie/laravel-pdf#177]
### What happened?

I can't see header and footer in my PDF.

Any idea? I can't find any solutions on internet...

### How to reproduce the bug

My controller:
```
return Pdf::view('pdf.invoice', ['invoice' => $invoice])
                ->headerView('pdf.invoice.header')
                ->footerView('pdf.invoice.footer')
                ->format(Format::A4)
                ->name('invoice.pdf');
```

My pdf.invoice.blade.php
```
<style>
    {!! Vite::content('resources/css/invoice.css') !!}
</style>
<div>some pdf body</div>
```

My pdf.invoice.footer.blade.php
```
<style>
    footer {
        padding: 0.5rem;
        padding-top: 0.25rem;
    }

    footer div p {
        color: black;
        font-size: 16px;
    }

</style>

<footer>
    <div>
        <p>Page @pageNumber of @totalPages</p>
    </div>
</footer>
```

pdf.invoice.header is almost same...

PDF rendered OK, but header and footer is (maybe) under main content. I don't know. When i select all text, i see footer and header text.

![image](https://github.com/user-attachments/assets/3ee7711b-e2c0-49da-854f-a1ed1ab5077a)

### Package Version

1.5.2

### PHP Version

8.3

### Laravel Version

11.20

### Which operating systems does with happen with?

Windows, Linux

**Comment by hurycz** [comment]
I found solutions (transparent background with margins)
**Documentation needs to be fixxed** how to use header/footer.
```
return Pdf::view('pdf.invoice', ['invoice' => $invoice])
                ->withBrowsershot(function (Browsershot $browsershot) {
                    $browsershot->transparentBackground();
                })
                ->margins(14,0,14,0)
                ->headerView('pdf.invoice.header')
                ->footerView('pdf.invoice.footer')
                ->format(Format::A4)
                ->name('invoice.pdf')
                ->save(storage_path("invoice.pdf"));
```

**Comment by gabriellara181999** [comment]
tengo el mismo problema pero no me funciona

**Comment by SecurID** [comment]
I can confirm I have the same error

**Comment by ArielMejiaDev** [comment]
@SecurID @gabriellara181999 @hurycz @kevin-netsrik you should add a font-size in your `header` and `footer` components, with that you are going to be able to see the text there

**Comment by memiljamel** [comment]
> [@SecurID](https://github.com/SecurID) [@gabriellara181999](https://github.com/gabriellara181999) [@hurycz](https://github.com/hurycz) [@kevin-netsrik](https://github.com/kevin-netsrik) you should add a font-size in your and components, with that you are going to be able to see the text there`header``footer`

awesome

**Comment by memiljamel** [comment]
> [@SecurID](https://github.com/SecurID) [@gabriellara181999](https://github.com/gabriellara181999) [@hurycz](https://github.com/hurycz) [@kevin-netsrik](https://github.com/kevin-netsrik) you should add a font-size in your `header` and `footer` components, with that you are going to be able to see the text there

wow, awesome.

**Comment by stuartcusackie** [comment]
Same problem. None of the solutions worked.  I removed my tailwind classes too.

```
<div style="padding: 1.25rem; font-size: 0.7rem; line-height: 1rem; width:100%;">
    <div style="justify-content: space-between; align-items: flex-center; display: flex;">
        <div>
            <p>Page @pageNumber of @totalPages</p>
        </div>

        <div style="text-align: right;">
            <p>created on <a href="https://xxx.io" target="_blank">xxx.io</a></p>
        </div>
    </div>
</div>

```

**Comment by edstevo** [comment]
@stuartcusackie - did you ever find a solution for custom fonts in the footer? Thank you
