### ISSUE TITLE
[Bug]: Minimum stability

### ISSUE THREAD

**Issue by Hladenkyi** [spatie/laravel-pdf#3]
### What happened?

Hi. I can't install the package on Laravel 10 because I have "minimum-stability" set in composer.josn (and in Laravel 10 it is by default): "stable".

![5bce41a6-9999-418f-8820-89f1035c1290](https://github.com/spatie/laravel-pdf/assets/30920864/9fc15e0c-ce7a-4d97-b9ae-138156e4d38c)

### How to reproduce the bug

Install package to laravel 10 where "minimum-stability" set to  "stable".

### Package Version

0.0.4

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by freekmurze** [comment]
A stable release will be tagged soon.
