### ISSUE TITLE
spatie/browsershot(4) require php ^8.2, but the package require php ^8.1

### ISSUE THREAD

**Issue by SneherAdor** [spatie/laravel-pdf#38]
### What happened?

`spatie/browsershot[4.0.0, ..., 4.0.1] require php ^8.2`

### How to reproduce the bug

While installing the package

### Package Version

1.1

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by freekmurze** [comment]
I've fixed the required PHP version.
