### ISSUE TITLE
[Bug]: Example test failing - undefined method

### ISSUE THREAD

**Issue by elijahworkz** [spatie/laravel-pdf#39]
### What happened?

when running an example of the test provided in the description I get an error that method doesn't exist:
` Call to undefined method Spatie\LaravelPdf\FakePdfBuilder::assertDownloaded()`

### How to reproduce the bug

Copy the test provided in documentation. (I do have a controller and a page that renders html)

### Package Version

2.0.0

### PHP Version

8.2.14

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by freekmurze** [comment]
This is the correct way to do this

https://github.com/spatie/laravel-pdf/blob/a61514ca413dade3d5aa01add77712fb3ced078d/tests/FakePdfTest.php#L122-L124

**Comment by elijahworkz** [comment]
@freekmurze  thanks!
But perhaps the descriptions in your repo and on your site should be updated?

https://spatie.be/docs/laravel-pdf/v1/introduction
