### ISSUE TITLE
[Bug]: Footer is extremely small

### ISSUE THREAD

**Issue by JasonJensenDev** [spatie/laravel-pdf#59]
### What happened?

First, thank you for all your do! I'm a huge Spatie fan.

I'm generating a proposal with the following code in my controller:

```
return pdf()
    ->view('documents.proposal', ['property' => $property])
    ->footerView('documents.footer')
    ->margins(10,10,10,10)
    ->name(now()->format('Y-m-d').' - '.$property->name );
```
The documents.footer is simply:
```
<div>
  page @pageNumber of @totalPages
</div>
```

The document body renders just fine, but the footer is so small that I almost didn't even see it. See screenshot:
![Screenshot 2024-01-25 at 5 36 54 PM](https://github.com/spatie/laravel-pdf/assets/74213705/25eeecff-1791-43ac-9d16-f011fe2340c4)

### How to reproduce the bug

I'm running on a Mac and this happens for both headers and footers, even if there is no special formatting in the body or the header/footer.

### Package Version

1.1.2

### PHP Version

8.2.15

### Laravel Version

v10.42.0

### Which operating systems does with happen with?

macOS

**Comment by ArielMejiaDev** [comment]
You need to set in your footer component a `font-size` as a style attribute or using a style tag in your component and reference it

The Footer and Header does not follow css from the body, this is basically by the way puppeteer render a whole PDF, it uses different process for Header and Footer and different process for the content, so you can use some css framework for the content but for header and footer you would require to set the css directly there, eg:

```php documents.footer.php
<style>
footer {
    font-size: 12px;
}
</style>

<footer>
  page @pageNumber of @totalPages
</div>
```

**Comment by JasonJensenDev** [comment]
That was it! Thank you!

**Comment by freekmurze** [comment]
Thanks for this example, I've added it to our docs.
