### ISSUE TITLE
[Bug]: Footer not visible

### ISSUE THREAD

**Issue by coreyfreeman82** [spatie/laravel-pdf#66]
### What happened?

When I try to load a footer on each page it is findable using browser search and find but not visible on pdf
#65 

### How to reproduce the bug

Have a blade with a html document including @pageBreak and load footer using footerView

### Package Version

1.1.2

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by freekmurze** [comment]
Make sure you provide CSS for the footer too as mentioned in the docs.

**Comment by coreyfreeman82** [comment]
This is my footer blade, does have css and is invisible
```
<style>
    .footer {
        font-size: 12px;
        margin: 10px auto;
        z-index: 999999;
    }
</style>

<footer>
    <div>
        <p>Page @pageNumber of @totalPages</p>
    </div>
    <div>
        <img src="{{$logo}}" width="300" alt="">
    </div>
</footer>
```
