### ISSUE TITLE
[Bug]: @inlinedImage only works with static urls

### ISSUE THREAD

**Issue by okaufmann** [spatie/laravel-pdf#84]
### What happened?

The new Blade directive `@inlinedImage` only works when passing static strings as image URLs or paths. When dynamically passing value from a Variable it does not work, as it does not resolve the value correctly.

**This does work:**
```blade
<div>
   @inlinedImage('https://picsum.photos/200/300')
</div>
```

**This does NOT work:**
```blade
<div>
   @php $src = 'https://picsum.photos/200/300' @endphp
   @inlinedImage($src)
</div>
```

This is an example of an Error I've got:

```
file_get_contents(public/$src): Failed to open stream: No such file or directory
```

Should a Blade directive not just return valid PHP source code to be evaluated by the view engine to work properly?

IMHO this should be more like this:

```php
Blade::directive('inlinedImage', function ($expression) {
            return "<?php
                \$url = \Illuminate\Support\Str::of(with({$expression}))->trim(\"'\")->trim('\"')->__toString();
        
                if (! \Illuminate\Support\Str::of(\$url)->startsWith(['http://', 'https://'])) {
                    \$path = public_path(\$url);
                    if (file_exists(\$path)) {
                        \$imageContent = 'data:image/png;base64,' . base64_encode(file_get_contents(\$path));
                        echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
                    }
                } else {
                    try {
                        \$response = \Illuminate\Support\Facades\Http::get(\$url);
                        if (\$response->successful()) {
                            \$imageContent = 'data:image/png;base64,' . base64_encode(\$response->body());
                            echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
                        }
                    } catch (\Exception \$e) {
                        throw new \RuntimeException('Failed to fetch the image: ' . \$e->getMessage());
                    }
                }
            ?>";
        });
```

If someone can confirm this error does occur too, I will create a PR for fixing this.

### How to reproduce the bug

Use the `inlinedImage` Blade directive provided by this package.

```blade
<div>
   @php $src = 'https://picsum.photos/200/300' @endphp
   @inlinedImage($src)
</div>
```

### Package Version

1.2.0

### PHP Version

8.2.0

### Laravel Version

10.43.0

### Which operating systems does with happen with?

macOS

**Comment by RVP04** [comment]
Will check and update you . Because I am not passing as a variable

**Comment by okaufmann** [comment]
@ArielMejiaDev Thank you for explaining this. The only thing that is still not working is, that the error handling is not happening at the right place. The error you forced by setting a non-existing URL was not a RuntimeException.

This is what I do have right now:

```php
Blade::directive('inlinedImage', function ($url) {
            return "<?php
                \$url = \Illuminate\Support\Str::of(with({$url}))->trim(\"'\")->trim('\"')->__toString();
        
                if (! \Illuminate\Support\Str::of(\$url)->startsWith(['http://', 'https://'])) {
                    \$path = public_path(\$url);
                    if (file_exists(\$path)) {
                        \$imageContent = 'data:image/png;base64,' . base64_encode(file_get_contents(\$path));
                        echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
                    }
                } else {
                    try {
                        \$response = \Illuminate\Support\Facades\Http::get(\$url);
                        if (\$response->successful()) {
                            \$imageContent = 'data:image/png;base64,' . base64_encode(\$response->body());
                            echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
                        }
                    } catch (\Exception \$e) {
                        throw new \RuntimeException('Failed to fetch the image: ' . \$e->getMessage());
                    }
                }
            ?>";
        });
       
  ```
  
  Can you confirm?

**Comment by ArielMejiaDev** [comment]
> @ArielMejiaDev Thank you for explaining this. The only thing that is still not working is, that the error handling is not happening at the right place. The error you forced by setting a non-existing URL was not a RuntimeException.
> 
> This is what I do have right now:
> 
> ```
> Blade::directive('inlinedImage', function ($url) {
>             return "<?php
>                 \$url = \Illuminate\Support\Str::of(with({$url}))->trim(\"'\")->trim('\"')->__toString();
>         
>                 if (! \Illuminate\Support\Str::of(\$url)->startsWith(['http://', 'https://'])) {
>                     \$path = public_path(\$url);
>                     if (file_exists(\$path)) {
>                         \$imageContent = 'data:image/png;base64,' . base64_encode(file_get_contents(\$path));
>                         echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
>                     }
>                 } else {
>                     try {
>                         \$response = \Illuminate\Support\Facades\Http::get(\$url);
>                         if (\$response->successful()) {
>                             \$imageContent = 'data:image/png;base64,' . base64_encode(\$response->body());
>                             echo '<img src=\"' . \$imageContent . '\" style=\"display:inline;\">';
>                         }
>                     } catch (\Exception \$e) {
>                         throw new \RuntimeException('Failed to fetch the image: ' . \$e->getMessage());
>                     }
>                 }
>             ?>";
>         });
>        
> ```
> 
> Can you confirm?

Thanks @okaufmann let me check, thanks

**Comment by ArielMejiaDev** [comment]
Thanks @okaufmann for your feedback, based on this discussion I think we got a solutions that resolves the issue and always returns an exception when it fails:

# The Last commits make `@inlinedImage`:

[x] Works with static string as params
[x] Works with variables as params
[x] Cleanup Blade Directive Code
[x] Always returns an exception if an image fails to fetch (absolute path) or is not found (relative path)

## Demo

https://www.loom.com/share/a7a760129c93452cb1006ff4cf21de53?sid=73be0c89-de9b-4367-aa6a-8b4c5118bdc1

It should close #84

**Comment by freekmurze** [comment]
We'll handle this further in #85
