### ISSUE TITLE
[Bug]: Problem showing image in PDF in production

### ISSUE THREAD

**Issue by sabinnitu** [spatie/laravel-pdf#87]
### What happened?

Hello,

I have a problem when I try to display an image only on the production server. Locally, the image works. I also have a development server _(same settings and configuration as production)_ where the image also works.

Code:
`<img src="{{ config('app.url') . "/" . $configuration->image_path }}" />`

The only difference that I saw was that in dev server the route of the image starts with http and on production server starts with https. (because of the .env config). So I change the code like this:

```
@if(app()->environment('production'))
<img src="{{ "http://example.com//“ . $configuration->image_path }}" />
@else
<img src="{{ config('app.url') . "/" . $configuration->image_path }}" />
@endif
```

Same problem. How can I fix this problem?
Thank you!

### How to reproduce the bug

Problem when I try to display an image only on the production server. _(images url starts with https)_

### Package Version

1.2.0

### PHP Version

8.2

### Laravel Version

10.44.0

### Which operating systems does with happen with?

macOS

**Comment by RVP04** [comment]
Check discussion #71

**Comment by sabinnitu** [comment]
Thank you @RVP04 for the reply.

**Comment by sabinnitu** [comment]
I'm back with the solution to my problem. After I used: `PdfImageAsset::make($path);` _(solution provided by @ArielMejiaDev   in @RVP04)_ in production, I had the following error in the my logs:

`cURL error 60: SSL certificate problem: unable to get local issuer certificate`

I solved the problem with the following code:

```
$image_path = ‘/images/example.webp’;
$image = storage_path($image_path);

Pdf::view('pdf', [
    ‘image' => 'data:image/png;base64,' . base64_encode(file_get_contents(image))
])
```

I hope it helps.
