### ISSUE TITLE
[Bug]: Unable to pass data to footerView when using Pdf::default in a Service Provider

### ISSUE THREAD

**Issue by 77media-creations** [spatie/laravel-pdf#88]
### What happened?

Trying to pass some data to the footerView.

This works:
```
// InvoiceController
Pdf::view('invoice')
    ->footerView('pdf.footer', ['siteName' => $site->name])
    ->save($pathToPdf);
```

BUT, when setting the defaults for footerView in a service container, there is no way to pass data to the footer:
```
use Spatie\LaravelPdf\Facades\Pdf;
use Spatie\LaravelPdf\Enums\Format;

// in a service provider

Pdf::default()
   ->footerView('pdf.footer')
    ->paperFormat(Format::A4);

// How to pass $site->name to the footer view here???
```

### How to reproduce the bug

Pass some data to the footer view in a service provider.

```
use Spatie\LaravelPdf\Facades\Pdf;
use Spatie\LaravelPdf\Enums\Format;

// in a service provider

Pdf::default()
   ->footerView('pdf.footer', ['siteName' => $site->name])    <<<<<<<<<<<<<<
    ->paperFormat(Format::A4);
```

### Package Version

1.2.0

### PHP Version

8.2.10

### Laravel Version

10.44.0

### Which operating systems does with happen with?

macOS

**Comment by freekmurze** [comment]
There is a test that proves that this works: https://github.com/spatie/laravel-pdf/blob/e5fab45dc16a27348ec2f6b20569ceae5559b657/tests/PdfTest.php#L70-L79
