### ISSUE TITLE
[Bug]: optional parameter in `download()` method is required

### ISSUE THREAD

**Issue by vintagesucks** [spatie/laravel-pdf#95]
### What happened?

The [docs](https://spatie.be/docs/laravel-pdf/v1/basic-usage/responding-with-pdfs) suggest combining `name()` with `download()` like this:

https://github.com/spatie/laravel-pdf/blob/68f48d23770d0b70f8fb0d32640d013d4b4023d4/docs/basic-usage/responding-with-pdfs.md#L35-L38

`download` does not require `$downloadName` to be set, but passes `$downloadName` to `name()`, which does:

https://github.com/spatie/laravel-pdf/blob/68f48d23770d0b70f8fb0d32640d013d4b4023d4/src/PdfBuilder.php#L138-L140

https://github.com/spatie/laravel-pdf/blob/68f48d23770d0b70f8fb0d32640d013d4b4023d4/src/PdfBuilder.php#L159

This results in the following error when calling `download()` without `$downloadName`:

```
Spatie\LaravelPdf\PdfBuilder::name(): Argument #1 ($downloadName) must be of type string, null given
```

### How to reproduce the bug

Use `download()` without an argument, as allowed by the method signature.

### Package Version

1.3.0

### PHP Version

8.2.16

### Laravel Version

10.45.0

### Which operating systems does with happen with?

macOS

**Comment by bluecraank** [comment]
Same issue today, but thanks to your issue solved :D

**Comment by freekmurze** [comment]
This has been fixed in the latest release.
